---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app
  namespace: argocd
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  project: app
  source:
    helm:
      values: |
        image:
          name: blusik99/app
          tag: 1.0
    chart: app
    repoURL: https://kamilblaz.github.io/argo-charts/
    targetRevision: 0.0.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
