---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-app
  namespace: argocd
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      values: |
        build:
          enabled: false
        deploy:
          route:
            tls:
              enabled: true
        image:
          name: quay.io/ablock/gitops-helm-quarkus
    chart: quarkus
    repoURL: https://kamilblaz.github.io/argo-charts/
    targetRevision: 0.0.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
